window['Company'] = class Company{
    constructor(){
        this.get = {
            id: 'Company',
            texts: {
                title: 'Empresa',
                search: null,
                add: null,
                register: null,
            },
            endpoint: 'company',
            bulk: null,
            call: null,
            filter: null,
            columns: null,
        }
        this.set = {
            general: {
                name: 'Geral',
                type: 'normal',
                fields: {
                    name: {
                        name: 'Nome',
                        width: {
                            desktop: 100,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o nome',
                            length: '50',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    company: {
                        name: 'Razão social',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite a razão social',
                            length: '100',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    document: {
                        name: 'CPF/CNPJ',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o CPF/CNPJ',
                            length: null,
                            mask: 'document',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    email: {
                        name: 'Email',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o email',
                            length: '100',
                            mask: 'email',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    site: {
                        name: 'Site',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o site',
                            length: '100',
                            mask: 'site',
                            prev: 'https://',
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    phone: {
                        name: 'Telefone',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o telefone',
                            length: null,
                            mask: 'phone',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    whatsapp: {
                        name: 'Whatsapp',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o whatsapp',
                            length: null,
                            mask: 'phone',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    logo: {
                        name: 'Logotipo',
                        width: {
                            desktop: 100,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: null,
                        select: null,
                        list: null,
                        image: {
                            type: 'normal',
                            max: 1,
                        },
                    },
                },
            },
            addresses: {
                name: 'Endereço',
                type: 'normal',
                fields: {
                    zip_code: {
                        name: 'CEP',
                        width: {
                            desktop: 20,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o CEP',
                            length: null,
                            mask: 'zip_code',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    address: {
                        name: 'Endereço',
                        width: {
                            desktop: 60,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o endereço',
                            length: '100',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    number: {
                        name: 'Número',
                        width: {
                            desktop: 20,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o número',
                            length: null,
                            mask: 'number',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    district: {
                        name: 'Bairro',
                        width: {
                            desktop: 40,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o bairro',
                            length: '50',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    city: {
                        name: 'Cidade',
                        width: {
                            desktop: 40,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite a cidade',
                            length: '50',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    state: {
                        name: 'Estado',
                        width: {
                            desktop: 20,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: null,
                        select: {
                            options: [
                                {name: "Acre", value: "AC"},
                                {name: "Alagoas", value: "AL"},
                                {name: "Amapá", value: "AP"},
                                {name: "Amazonas", value: "AM"},
                                {name: "Bahia", value: "BA"},
                                {name: "Ceará", value: "CE"},
                                {name: "Distrito Federal", value: "DF"},
                                {name: "Espírito Santo", value: "ES"},
                                {name: "Goiás", value: "GO"},
                                {name: "Mato Grosso", value: "MT"},
                                {name: "Mato Grosso do Sul", value: "MS"},
                                {name: "Minas Gerais", value: "MG"},
                                {name: "Pará", value: "PA"},
                                {name: "Paraíba", value: "PB"},
                                {name: "Paraná", value: "PR"},
                                {name: "Pernambuco", value: "PE"},
                                {name: "Piauí", value: "PI"},
                                {name: "Rio de Janeiro", value: "RJ"},
                                {name: "Rio Grande do Norte", value: "RN"},
                                {name: "Rio Grande do Sul", value: "RS"},
                                {name: "Rondônia", value: "RO"},
                                {name: "Roraima", value: "RR"},
                                {name: "Santa Catarina", value: "SC"},
                                {name: "São Paulo", value: "SP"},
                                {name: "Sergipe", value: "SE"},
                                {name: "Tocantins", value: "TO"},
                            ],
                        },
                        list: null,
                        image: null,
                    },
                    complement: {
                        name: 'Complemento',
                        width: {
                            desktop: 100,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o complemento',
                            length: '100',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                },
            },
        }
    }
    custom(database=null,attr=null){
        return false;
    }
    customGet(database=null,attr=null){
        return false;
    }
    customSet(database=null,attr=null){
        $('.top__name').text('Empresa');
        $('.up__title').text('Empresa');
        $('.top__return').hide();
        $('button[code="deletar"]').hide();
    }
}