window['Customers'] = class Customers{
    constructor(){
        this.get = {
            id: 'Customers',
            texts: {
                title: 'Clientes',
                search: 'Buscar em clientes',
                add: 'Novo cliente',
                register: 'Cadastre seu primeiro cliente.',
            },
            endpoint: 'customers',
            bulk: {
                activate: 'Ativar',
                deactivate: 'Desativar',
                delete: 'Excluir',
            },
            call: {
                date: rangeDate(),
                status: 'on',
            },
            filter: {
                date: {
                    name: 'Data',
                    type: 'date',
                    options: null,
                },
                status: {
                    name: 'Status',
                    type: 'select',
                    options: [
                        {name: 'Todos', value: ''},
                        {name: 'Ativo', value: 'on'},
                        {name: 'Inativo', value: 'off'},
                    ],
                },
            },
            columns: {
                status: {
                    name: null,
                    width: null,
                    row: null,
                },
                check: {
                    name: null,
                    width: null,
                    row: null,
                },
                date: {
                    name: 'Data',
                    width: 'date',
                    row: {
                        date: {
                            type: 'normal',
                            text: '[text]',
                            link: null,
                            mobile: true,
                        },
                        hour: {
                            type: 'normal',
                            text: '[text]',
                            link: null,
                            mobile: false,
                        },
                    },
                },
                name: {
                    name: 'Nome',
                    width: 40,
                    row: {
                        name: {
                            type: 'bold',
                            text: '[text]',
                            link: `set(['Customers'],'id')`,
                            mobile: true,
                        },
                    },
                },
                phone: {
                    name: 'Telefone',
                    width: 20,
                    row: {
                        phone: {
                            type: 'normal',
                            text: '[text]',
                            link: null,
                            mobile: true,
                        },
                    },
                },
                subscriptions: {
                    name: 'Assinaturas',
                    width: 20,
                    row: {
                        subscriptions: {
                            type: 'normal',
                            text: '[text] (assinatura/assinaturas)',
                            link: `get(['Subscriptions'],{customer:'id'})`,
                            mobile: false,
                        },
                    },
                },
                invoices: {
                    name: 'Faturas',
                    width: 20,
                    row: {
                        invoices: {
                            type: 'normal',
                            text: '[text] (fatura/faturas)',
                            link: `get(['Invoices'],{customer:'id'})`,
                            mobile: false,
                        },
                    },
                },
                edit: {
                    name: 'Editar',
                    width: null,
                    row: null,
                },
                delete: {
                    name: 'Excluir',
                    width: null,
                    row: null,
                },
            }
        }
        this.set = {
            general: {
                name: 'Geral',
                type: 'normal',
                fields: {
                    name: {
                        name: 'Nome',
                        width: {
                            desktop: 60,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o nome',
                            length: '100',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    document: {
                        name: 'CPF/CNPJ',
                        width: {
                            desktop: 40,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o CPF/CNPJ',
                            length: null,
                            mask: 'document',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    email: {
                        name: 'Email',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o email',
                            length: '100',
                            mask: 'email',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    site: {
                        name: 'Site',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o site',
                            length: '100',
                            mask: 'site',
                            prev: 'https://',
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    phone: {
                        name: 'Telefone',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: true,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o telefone',
                            length: null,
                            mask: 'phone',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    whatsapp: {
                        name: 'Whatsapp',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o whatsapp',
                            length: null,
                            mask: 'phone',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    answerable: {
                        name: 'Responsável',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o responsável',
                            length: '50',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    status: {
                        name: 'Status',
                        width: {
                            desktop: 50,
                            mobile: 100,
                        },
                        value: 'on',
                        required: true,
                        disabled: false,
                        input: null,
                        select: {
                            options: [
                                {name: 'Ativo', value: 'on'},
                                {name: 'Inativo', value: 'off'},
                            ],
                        },
                        list: null,
                        image: null,
                    },
                    note: {
                        name: 'Anotações',
                        width: {
                            desktop: 100,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'textarea',
                            holder: 'Digite as anotações',
                            length: '500',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                },
            },
            addresses: {
                name: 'Endereço',
                type: 'normal',
                fields: {
                    zip_code: {
                        name: 'CEP',
                        width: {
                            desktop: 20,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o CEP',
                            length: null,
                            mask: 'zip_code',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    address: {
                        name: 'Endereço',
                        width: {
                            desktop: 60,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o endereço',
                            length: '100',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    number: {
                        name: 'Número',
                        width: {
                            desktop: 20,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o número',
                            length: null,
                            mask: 'number',
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    district: {
                        name: 'Bairro',
                        width: {
                            desktop: 40,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o bairro',
                            length: '50',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    city: {
                        name: 'Cidade',
                        width: {
                            desktop: 40,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite a cidade',
                            length: '50',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                    state: {
                        name: 'Estado',
                        width: {
                            desktop: 20,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: null,
                        select: {
                            options: [
                                {name: "Acre", value: "AC"},
                                {name: "Alagoas", value: "AL"},
                                {name: "Amapá", value: "AP"},
                                {name: "Amazonas", value: "AM"},
                                {name: "Bahia", value: "BA"},
                                {name: "Ceará", value: "CE"},
                                {name: "Distrito Federal", value: "DF"},
                                {name: "Espírito Santo", value: "ES"},
                                {name: "Goiás", value: "GO"},
                                {name: "Mato Grosso", value: "MT"},
                                {name: "Mato Grosso do Sul", value: "MS"},
                                {name: "Minas Gerais", value: "MG"},
                                {name: "Pará", value: "PA"},
                                {name: "Paraíba", value: "PB"},
                                {name: "Paraná", value: "PR"},
                                {name: "Pernambuco", value: "PE"},
                                {name: "Piauí", value: "PI"},
                                {name: "Rio de Janeiro", value: "RJ"},
                                {name: "Rio Grande do Norte", value: "RN"},
                                {name: "Rio Grande do Sul", value: "RS"},
                                {name: "Rondônia", value: "RO"},
                                {name: "Roraima", value: "RR"},
                                {name: "Santa Catarina", value: "SC"},
                                {name: "São Paulo", value: "SP"},
                                {name: "Sergipe", value: "SE"},
                                {name: "Tocantins", value: "TO"},
                            ],
                        },
                        list: null,
                        image: null,
                    },
                    complement: {
                        name: 'Complemento',
                        width: {
                            desktop: 100,
                            mobile: 100,
                        },
                        value: '',
                        required: false,
                        disabled: false,
                        input: {
                            type: 'text',
                            holder: 'Digite o complemento',
                            length: '100',
                            mask: null,
                            prev: null,
                            next: null,
                            button: null,
                        },
                        select: null,
                        list: null,
                        image: null,
                    },
                },
            },
            groups: {
                name: 'Grupos',
                type: 'multi',
                fields: {
                    groups: {
                        name: 'Grupo',
                        width: {
                            desktop: 100,
                            mobile: 100,
                        },
                        value: 'Nenhuma',
                        required: true,
                        disabled: false,
                        input: null,
                        select: null,
                        list: {
                            type: 'text',
                            options: [],
                        },
                        image: null,
                    },
                },
            },
        }
    }
    custom(database=null,attr=null){
        return false;
    }
    customGet(database=null,attr=null){
        return false;
    }
    customSet(database=null,attr=null){
        return false;
    }
}